import { useState } from 'react';
import { motion } from 'framer-motion';
import SectionDivider from './SectionDivider';

/**
 * Live snake contribution grid, generated by the Platane/snk GitHub Action on the
 * `output` branch of the profile README repo — so it re-renders itself every time
 * that action runs. Both variants currently resolve to the same file upstream.
 */
const SNAKE_URL =
  'https://raw.githubusercontent.com/Abdullah-JUTT-cloud/Abdullah-JUTT-cloud/output/github-contribution-grid-snake.svg';
const SNAKE_FALLBACK_URL =
  'https://raw.githubusercontent.com/Abdullah-JUTT-cloud/Abdullah-JUTT-cloud/output/github-contribution-grid-snake-dark.svg';

const GITHUB_URL = 'https://github.com/Abdullah-JUTT-cloud';

const GitHubActivity = () => {
  // One-shot fallback: swapping again on a second failure would loop forever.
  const [snakeSrc, setSnakeSrc] = useState(SNAKE_URL);

  return (
    <section
      id="github"
      className="bg-[#05050a] pt-20 pb-40 px-6 md:px-12 w-full relative overflow-x-clip font-sans"
    >
      <div className="max-w-6xl mx-auto relative z-10">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="inline-block px-4 py-1 rounded-full bg-[#ff2a2a]/10 border border-[#ff2a2a]/30 text-[#ff2a2a] text-xs font-bold tracking-widest uppercase mb-4">
            Open Source // GitHub
          </div>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-black text-white tracking-tight leading-[1.05]">
            Contribution
            <span className="block text-[#ff2a2a]">Activity</span>
          </h2>
          <p className="text-gray-400 text-sm md:text-base mt-4 max-w-2xl leading-relaxed">
            Every square is a day of building, breaking, and shipping — regenerated
            straight from my GitHub profile, so it is always current.
          </p>
        </motion.div>

        {/* Snake Contribution Grid */}
        <motion.div
          initial={{ opacity: 0, y: 25 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="bg-gray-900 border border-white/10 rounded-3xl p-4 md:p-6 mb-8 overflow-hidden hover:border-[#ff2a2a]/40 transition-colors duration-500"
        >
          <img
            src={snakeSrc}
            alt="Animated snake eating through Muhammad Abdullah's GitHub contribution grid"
            onError={() =>
              setSnakeSrc((current) =>
                current === SNAKE_URL ? SNAKE_FALLBACK_URL : current
              )
            }
            draggable="false"
            className="w-full h-auto select-none pointer-events-none"
          />
        </motion.div>

        {/* Single CTA — matches the hero's GitHub button treatment */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.4, delay: 0.15 }}
        >
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-6 py-2.5 md:px-7 md:py-3 text-xs md:text-sm rounded-full bg-black/40 border border-white/20 text-white/80 font-bold hover:bg-white hover:text-black transition-all duration-300 backdrop-blur-md transform hover:-translate-y-0.5 text-center"
          >
            View GitHub ↗
          </a>
        </motion.div>
      </div>

      {/* Wave transition into Education (red) */}
      <SectionDivider aboveColor="#05050a" belowColor="#ff2a2a" />
    </section>
  );
};

export default GitHubActivity;
